name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dimamihi/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true dimamihi/react-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output-artifacts
          path: |
            deploy.zip